export const config = [
    "Replicate",
    "Sample",
    "Disabled",
    "Notes",
    {
        from: "ID",
        to: "Run Date",
    },
    "Analysis",
    "Analysis Status",
    "Mass Spec",
    "Easotope Name",
    "Sample Type",
    "Corr Interval",
    "Acid Temp",
    {
        from: "d13C VPDB (Raw)",
        summary: ["stdErr"],
    },
    "d13C VPDB (Raw) SE",
    {
        from: "d18O VPDB (Raw)",
        summary: ["stdErr"],
    },
    "d18O VPDB (Raw) SE",
    {
        from: "d18O VSMOW (Raw)",
        summary: ["stdErr"],
    },
    "d18O VSMOW (Raw) SE",
    {
        from: "d47 WG (Raw)",
        summary: ["stdErr"],
    },
    "d47 WG (Raw) SE",
    {
        from: "D47 WG (Raw)",
        summary: ["stdErr"],
    },
    "D47 WG (Raw) SE",
    {
        from: "d48 WG (Raw)",
        summary: ["stdErr"],
    },
    "d48 WG (Raw) SE",
    {
        from: "D48 WG (Raw)",
        summary: ["stdErr"],
    },
    "D48 WG (Raw) SE",
    {
        from: "d49 WG (Raw)",
        summary: ["stdErr"],
    },
    "d49 WG (Raw) SE",
    {
        from: "D49 WG (Raw)",
        summary: ["stdErr"],
    },
    "D49 WG (Raw) SE",
    "D47 Nonlinearity Slope",
    "D47 Nonlinearity Intercepts",
    "D47 WG (HG)",
    "D47 ETF Slope",
    "D47 ETF Intercept",
    "D47 CDES (ETF)",
    {
        from: "D47 AFF",
        to: "D47 Acid Fractionation Factor",
    },
    "D48 Nonlinearity Slope",
    "D48 Nonlinearity Intercepts",
    "D48 WG (HG)",
    "D48 ETF Slope",
    "D48 ETF Intercept",
    "D48 CDES (ETF)",
    {
        from: "D48 AFF",
        to: "D48 Acid Fractionation Factor",
    },
    {
        from: "d13C VPDB (Final)",
        to: "δ13C VPDB (Final)",
        summary: ["average", "stdDev"],
    },
    {
        from: "d18O VPDB (Final)",
        to: "δ18O VPDB (Final)",
        summary: ["average", "stdDev"],
    },
    {
        from: "d18O VSMOW (Final)",
        to: "δ18O VSMOW (Final)",
        summary: ["average", "stdDev"],
    },
    {
        from: "D47 CDES (Final)",
        to: "Δ47 CDES (Final)",
        summary: ["average", "stdErr"],
    },
    "Δ47 CDES (Final) SE",
    {
        from: "D48 CDES (Final)",
        to: "Δ48 CDES (Final)",
        summary: ["average", "stdErr"],
    },
    "Δ48 CDES (Final) SE",
    "Temperature Calibration slope (Anderson et al. 2021)",
    "Temperature Calibration intercept (Anderson et al. 2021)",
    "Temp [°C]",
    "Temp [°C] average",
    "+/- SE",
    "Predicted Alpha (NOTE: mineral specific)",
    "Predicted Alpha average (NOTE: mineral specific)",
    "water δ18O VSMOW",
    "water δ18O VSMOW average",
    "water δ18O VSMOW standard deviation",
];
